install.packages("dplyr",repos="http://cran.rstudio.com")
install.packages("ggplot2",repos="http://cran.rstudio.com")
install.packages("stringr",repos="http://cran.rstudio.com")
install.packages("data.table",repos="http://cran.rstudio.com")
install.packages("readr",repos="http://cran.rstudio.com")